version: "3.8"

services:
  x-data-scrapper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: x-data-scraper
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      - PORT=1337
    env_file:
      - .env
    volumes:
      - ./out:/app/out
    restart: unless-stopped
    mem_limit: 2g
    cpus: 2
    shm_size: 2gb
